### ISSUE TITLE
Nothing happens when Login button is pressed

### ISSUE THREAD

**Issue by ssjw** [GoodAI/charlie-mnemonic#13]
Built on Mac (M2 Pro) with Brew installed postgresql.  I was able to register, but nothing happens when using the registered user to log in.  The console just reports `INFO:     127.0.0.1:61459 - "POST /login/ HTTP/1.1" 200 OK`.

It is validating the user, as entering a non-existent user generates a `User login failed` error and a `401 unauthorized` in the console output.

<img width="1184" alt="image" src="https://github.com/GoodAI/charlie-mnemonic/assets/10264409/ec191aab-a620-4a8f-a052-970d8e062b39">

**Comment by roengram** [comment]
Same problem here. And sign in google opens up an empty dialogue. I tried to set `SINGLE_USER=true` to bypass login but didn't seemt to work either.

**Comment by airobinnet** [comment]
I agree there is a lack of Mac support right now.

I'll try to get my hands on a Mac or set up a VM and look into this.

**Comment by finereli** [comment]
I'm running the Docker setup via docker-compose on Ubuntu and getting the same thing - Google auth shows an empty window and Login doesn't do anything.

**Comment by airobinnet** [comment]
This will be fixed for Linux in the next update
![image](https://github.com/GoodAI/charlie-mnemonic/assets/126980386/6db69a67-aada-4060-9538-eeaf6d364766)

Should be working for Mac too with the next update

**Comment by airobinnet** [comment]
#21 Should address this, be sure to follow [https://github.com/GoodAI/charlie-mnemonic/blob/dev/docs/MACINSTALL.md](https://github.com/GoodAI/charlie-mnemonic/blob/dev/docs/MACINSTALL.md) or https://github.com/GoodAI/charlie-mnemonic/blob/dev/docs/LINUXINSTALL.md
