### ISSUE TITLE
DuckDuckGo search always fails with Rate Limit

### ISSUE THREAD

**Issue by SquidLord** [GoodAI/charlie-mnemonic#18]
Every time the system attempts to integrate the DuckDuckGo search function call, it fails with a rate limit issue. While the LLM recovers with a certain amount of grace, telling me that there has been an error, that doesn't make it actually function.

> processing function search_duckduckgo response: Error performing DuckDuckGo search: _aget_url() https://links.duckduckgo.com/d.js DuckDuckGoSearchException: Ratelimit

**Comment by airobinnet** [comment]
Can you check the latest build, an attempt to fix this has been added

https://github.com/GoodAI/charlie-mnemonic/blob/863d478b0d6be464430c501aed137e7e68032736/Dockerfile#L29
