### ISSUE TITLE
Becoming a Regular Contributor 

### ISSUE THREAD

**Issue by ShivamGupta42** [GoodAI/charlie-mnemonic#28]
I am strongly passionate about what you guys are building. As I am going through the code base, I see many areas in which we can improve e.g. decrease the implicit reliance on OpenAI APIs e.g. currently token use is based on GPT-4 even if you plan to use local LLM. 

In order for me to become a regular contributor, we need to decrease the MR review time to a few days. I feel a bit hesitant in raising MRs when I feel that they might get overlooked for weeks on end. I can contribute in both documentation and tech for this project. This is quite a niche project, I would love to have a short call with you guys about the project's future etc.

**Comment by airobinnet** [comment]
Contacted you!
